version: '3.8'

services:
  mysqlaccdb:
    image: mysql:5.7.22
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqlaccdb
    build: ./accelerate-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqlaccdb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  client:
    build: ./client
    depends_on:
      - app
    ports:
      - 80:8080
    env_file: ./.env
    volumes:
      - ./client:/data
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://localhost:$NODE_LOCAL_PORT/ 

volumes: 
  db: